# Generated by Django 3.2.7 on 2021-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=200, verbose_name='제목')),
                ('goal_money', models.IntegerField(default=0, help_text='만원단위로 입력하세요.', verbose_name='목표금액')),
                ('saving_money', models.IntegerField(default=0, help_text='만원단위로 입력하세요.', verbose_name='모은금액')),
            ],
        ),
    ]
