# Generated by Django 3.2.6 on 2021-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goldMoney', models.IntegerField()),
                ('currentMoney', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
                ('beforeExpense', models.IntegerField()),
                ('afterExpense', models.IntegerField()),
            ],
        ),
    ]
