# Generated by Django 3.2.7 on 2021-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='afterExpense',
            field=models.IntegerField(help_text='만', null=True, verbose_name='은퇴 후 월간'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(help_text='만', null=True, verbose_name='나의 나이'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='beforeExpense',
            field=models.IntegerField(help_text='만', null=True, verbose_name='은퇴 전 월간'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='currentMoney',
            field=models.IntegerField(help_text='만', null=True, verbose_name='현재 저축액'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='goldMoney',
            field=models.IntegerField(help_text='만', null=True, verbose_name='목표 저축액'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='salary',
            field=models.IntegerField(help_text='만', null=True, verbose_name='나의 연봉'),
        ),
    ]
